package desm.common;

/**
 * CO2 emission value in grams.
 * Timestamp is seconds after midnight (as generated by the simulator).
 */
public class Measurement {

    /** CO2 emission value in grams. */
    private final double value;

    /** Seconds after midnight (as produced by the sensor simulator). */
    private final long timestamp;

    public Measurement(double value, long timestamp) {
        this.value = value;
        this.timestamp = timestamp;
    }

    public double getValue() {
        return value;
    }

    public long getTimestamp() {
        return timestamp;
    }

    @Override
    public String toString() {
        return "Measurement{value=" + value + "g, timestamp=" + timestamp + "s}";
    }
}
